MVN-9 (Implement alternative configuration profile possibility)
AnastasiyaIlkevich/Movienote pull request #11
Opened 2021-09-28 20:10 UTC by NadezhdaPenkrat

Implement alternative configuration profile possibility

2021-09-29 18:50 UTC, RomanKashenok requested changes

2021-09-29 18:50 UTC, RomanKashenok commented on build.gradle
> +    implementation 'junit:junit:4.13.1'
зачем нам тестовый фреймворк, который конфликтует с поставляемым спрингом?

2021-09-29 18:50 UTC, RomanKashenok commented on build.gradle
> +    implementation 'junit:junit:4.13.1'
точнее не конфликтует конечно, но зачем нам две версии по сути одного и того же?

2021-09-29 18:50 UTC, RomanKashenok commented on src/main/java/com/movienote/config/DBConfiguration.java
> +    public String devDatabaseConnection() {
это что такое?

2021-09-29 18:50 UTC, RomanKashenok commented on src/main/java/com/movienote/config/DBConfiguration.java
> +    public String testDatabaseConnection() {
это что такое?

2021-09-29 18:50 UTC, RomanKashenok commented on src/main/java/com/movienote/config/DBConfiguration.java
> +    public String prodDatabaseConnection() {
это что такое?

2021-09-29 18:50 UTC, RomanKashenok commented on src/main/resources/application-dev.properties
> +#Dev ENVIRONMENT SETTING#
для чего нам 3 практически аналогичных файла конфигурации? Давай сделаем нормально - три РАЗНЫЕ конфигурации

2021-09-29 18:50 UTC, RomanKashenok commented on src/main/resources/application-test.properties
> +#Test ENVIRONMENT SETTING#
задай в этом конфиге данные для тестового запуска на основе встроенной базы данных Н2

2021-10-02 18:59 UTC, RomanKashenok approved these changes

2021-10-05 12:48 UTC, RomanKashenok requested changes

2021-10-05 12:48 UTC, RomanKashenok commented on src/main/resources/application.properties
> +spring.profiles.active=@activatedProperties@
расскажи зачем это надо

2021-10-05 12:48 UTC, RomanKashenok commented on src/main/resources/application-test.properties
> +spring.datasource.password=
здесь можно оставить - у всех одинаковые будут

2021-10-05 12:48 UTC, RomanKashenok commented on src/main/resources/application-prod.properties
> +spring.datasource.password=
прям правда ты планируешь разрабатывать на локальной postgres, что бы в проде использовать mysql? 
Выглядит как слишком легкая жизнь и ты хочешь её осложнить

2021-10-05 12:48 UTC, RomanKashenok commented on src/main/resources/application.properties
> +spring.datasource.password=
чем эти проперти должны отличаться от application-prod.properties?

2021-10-05 18:47 UTC, NadezhdaPenkrat commented on src/main/resources/application.properties
> +spring.profiles.active=@activatedProperties@
перенесла выбор  профиля с properties  в Configuration Spring Boot >'Active Profiles'

2021-10-05 19:02 UTC, NadezhdaPenkrat commented on src/main/resources/application-prod.properties
> +spring.datasource.password=
оставлю  postgres

2021-10-05 19:37 UTC, NadezhdaPenkrat commented on src/main/resources/application.properties
> +spring.datasource.password=
разные server.port

2021-10-07 10:04 UTC, merged