MVN-11 Implement services with CRUD operations (part: MVN-16 Implement userService)
AnastasiyaIlkevich/Movienote pull request #14
Opened 2021-10-07 15:24 UTC by AnastasiyaIlkevich

MVN-11 Implement services with CRUD operations (part: MVN-16 Implement userService)

2021-10-08 08:21 UTC, RomanKashenok requested changes

2021-10-08 08:21 UTC, RomanKashenok commented on src/main/java/com/movienote/controller/UserController.java
> +    UserServiceImplementation userService;
используй интерфейсы и внедрение через конструктор

2021-10-08 08:21 UTC, RomanKashenok commented on src/main/java/com/movienote/repository/UserJpaRepository.java
> +    void deleteByUsername(String username);
никогда не удалая не по ключу. При большой количестве записей это приведет к полному скану всей таблицы - это дорого и долго + при опечатке или неверном регистре ничего не даст

2021-10-08 08:21 UTC, RomanKashenok commented on src/main/java/com/movienote/service/UserServiceImplementation.java
> +        roles.add(roleJpaRepository.getById(1L));
а если у роли поменяется id?

2021-10-09 13:02 UTC, RomanKashenok commented on src/main/java/com/movienote/model/Movie.java
> +@JsonIdentityInfo(generator= ObjectIdGenerators.PropertyGenerator.class, property="id")
давай уберем это все лишнее и будем работать с моделью внутри, а с dto - между апи поиска и нашим приложением. 
Надо создать для этого Dto (вообще не понятно почему ты в рамках этой задачи ты делаешь маппинг на json объект themoviedb)

2021-10-09 13:29 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/controller/MovieController.java
> +    @GetMapping("/{title}")
Ипсравила, но я всё также не понимаю(

2021-10-09 16:27 UTC, RomanKashenok commented on src/main/java/com/movienote/model/Movie.java
> +@JsonIdentityInfo(generator= ObjectIdGenerators.PropertyGenerator.class, property="id")
я вообще слабо понимаю что тут модели делают, если задача - сделать сервисы, под уже готовые модели

2021-10-09 17:27 UTC, merged