MVN-4 (Implement model classes)
AnastasiyaIlkevich/Movienote pull request #4
Opened 2021-09-20 13:34 UTC by AnastasiyaIlkevich

есть недочеты

2021-09-21 18:10 UTC, RomanKashenok commented on src/main/java/com/movienote/model/Movie.java
> +    @ManyToMany(fetch = FetchType.EAGER)
ManyToMany означает, что у фильма есть много статусов (причем ссылка на статус, почему-то, хранится в таблице users_has_movies (мне кажется там на другой стороне юзеры, а не статусы)).

2021-09-21 18:11 UTC, RomanKashenok commented on src/main/java/com/movienote/model/User.java
> +    private String passwordConfirm;
а это зачем вообще?

2021-09-22 10:48 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/Genre.java
> +    @Column(name = "genres")
исправила

2021-09-22 10:52 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/Movie.java
> +    @ManyToMany(fetch = FetchType.EAGER)
исправила

2021-09-22 10:52 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/User.java
> +    private String passwordConfirm;
удалила. Думала на будущее

2021-09-22 10:56 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/Genre.java
> +public class Genre {
исправила

2021-09-25 12:19 UTC, RomanKashenok requested changes

2021-09-25 12:19 UTC, RomanKashenok commented on src/main/java/com/movienote/model/Movie.java
> +    @OneToMany (cascade = CascadeType.ALL, mappedBy="movie")
cascade = CascadeType.ALL
для чего нам тут такой каскад тайп? Обоснуй

2021-09-25 12:19 UTC, RomanKashenok commented on src/main/java/com/movienote/model/Status.java
> +    @OneToMany (cascade = CascadeType.ALL, mappedBy="status")
аналогично предыдущему

2021-09-25 12:19 UTC, RomanKashenok commented on src/main/java/com/movienote/model/User.java
> -@NoArgsConstructor
Есть причина, по которой убрана аннотация?

2021-09-25 12:19 UTC, RomanKashenok commented on src/main/java/com/movienote/model/UserMovies.java
> +    @Column(name = "reiting")
давай все же оставим грамматически правильное написание

2021-09-25 14:12 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/User.java
> -@NoArgsConstructor
У меня подсвечивается @Data, я смотрела по чему и случайно удалила, не заметив. Верну.

2021-09-25 14:22 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/Status.java
> +    @OneToMany (cascade = CascadeType.ALL, mappedBy="status")
Да, здесь моя ошибка. У меня была мысль, что если удалить юзера из базы, то и его комментарии в таблице" user_movies" тоже должны быть удалены. А дальше когда я делала соединение таблиц "statuses" и "movies" я просто скопировала, чтоб не печатать. И не пересмотрела (и даже не подумала, а нужны ли здесь каскадные операции). Если уж подумать. То нам не нужно удалять статусы и фильмы из базы если удалился один юзер.

2021-09-25 14:22 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/Movie.java
> +    @OneToMany (cascade = CascadeType.ALL, mappedBy="movie")
исправляю

2021-09-25 14:22 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/UserMovies.java
> +    @Column(name = "reiting")
исправляю

2021-09-26 10:14 UTC, AnastasiyaIlkevich commented on src/main/java/com/movienote/model/Status.java
> +    @OneToMany (cascade = CascadeType.ALL, mappedBy="status")
Исправила, но уверенности в правильном установлении CascadeType нет(((

2021-09-26 19:57 UTC, RomanKashenok approved these changes

2021-09-26 19:57 UTC, RomanKashenok commented on src/main/java/com/movienote/model/Genre.java
> +    @ManyToMany(mappedBy = "genres")
Lazy?

2021-09-27 09:06 UTC, merged