MVN-3 (Implement DB migration tool integration)
AnastasiyaIlkevich/Movienote pull request #5
Opened 2021-09-20 16:32 UTC by NadezhdaPenkrat

Using Liquibase with Spring Boot for PostgreSQL Database Migration

2021-09-21 18:48 UTC, RomanKashenok requested changes

2021-09-21 18:48 UTC, RomanKashenok commented on build.gradle
> +    id "org.akhikhl.gretty" version "1.2.4"
это что и зачем?

2021-09-21 18:48 UTC, RomanKashenok commented on build.gradle
> +    compile('org.springframework.boot:spring-boot-starter')
compile, как и compileOnly, testCompile и все, что с compile - устарело - убираем и ставим правильный скоуп

2021-09-21 18:48 UTC, RomanKashenok commented on build.gradle
> +task updateDbMain(dependsOn: startDatabase) {
кастомные таски из build.gradle убираем

2021-09-21 18:48 UTC, RomanKashenok commented on build.gradle
> +liquibase {
всё конфигурирование liquibase убираем из build.gradle и переносим в код (или в пропертях проекта прописываем нужные значения, что бы спринг сам все настроил)

2021-09-21 18:48 UTC, RomanKashenok commented on build.gradle
> +def dbUrl = project.properties['dbUrl'] ?: gradle.dbUrl
убираем объявления переменных отсюда

2021-09-21 18:48 UTC, RomanKashenok commented on build.gradle
> +plugins {
плагин не нужен

2021-09-21 18:48 UTC, RomanKashenok commented on build.gradle
> +apply from: 'database.gradle'
зачем и секция plugins и apply plugin? 
давайте что-то одно использовать

2021-09-21 18:48 UTC, RomanKashenok commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
все, что генерирует схему - убираем

2021-09-21 20:29 UTC, NadezhdaPenkrat commented on build.gradle
> +    id "org.akhikhl.gretty" version "1.2.4"
Gradle плагин для быстрого и удобного запуска контейнеров, думала может пригодиться

2021-10-04 19:41 UTC, anastaciatimohova requested changes
fixed and new

2021-10-09 11:31 UTC, RomanKashenok approved these changes

2021-10-09 12:28 UTC, merged